### ISSUE TITLE
QoS results not accessible

### ISSUE THREAD

**Issue by vraida** [rtr-nettest/open-rmbt-website#3]
Hi, according to the OpenData specs [https://www.netztest.at/en/OpenDataSpecification.html](https://www.netztest.at/en/OpenDataSpecification.html), the QoS results should be accessible via URL `INTERFACE/qos/<open-test-uuid>`.

However, this doesn't seem to work.
Whereas the access to .json file https://www.netztest.at/opendata/opentests/O56b5cc79-5669-4457-bce2-0aeaf3b7242f works fine, the QoS URL https://www.netztest.at/opendata/qos/O56b5cc79-5669-4457-bce2-0aeaf3b7242f yields "502 Bad Gateway" error.

Best regards,
Vaclav

**Comment by cproof** [comment]
Hi @vraida ,
thank you for reporting this issue.
We have resolved this on the server side, it should now work again as specified, e.g. https://www.netztest.at/opendata/qos/Oe96bf42d-3b51-4ae0-ab35-f2c6cf74322a/de 
Best regards

**Comment by vraida** [comment]
Perfect, thanks a lot!
