### ISSUE TITLE
Not working on iphone

### ISSUE THREAD

**Issue by Dandashii** [rtr-nettest/open-rmbt-website#5]
why is the browser test not working on the mac or any iphone?

**Comment by cproof** [comment]
The problem is that on latest iOS versions, iOS breaks websocket in upload.
See https://developer.apple.com/forums/thread/685403?login=true

This can be solved by Setting safari =>Advanced=>Experimental Features=>NSURLSession WebSocket to off, but it cannot be automatically detected.

**Comment by Dandashii** [comment]
Any work around on this issue without having to change anything in my safari settings or you will have to wait for apple to fix this issue in a patch?

**Comment by cproof** [comment]
We did not find a workaround. If you find one, we're happy to apply.
Otherwise we have to wait for Apple to fix it.

**Comment by GreatDandashi** [comment]
https://developer.apple.com/forums/thread/685403?page=3

The latest comment says that this problem is fixed in the latest 15.4 update.

Can you confirm?

**Comment by Dandashii** [comment]
https://developer.apple.com/forums/thread/685403?page=3

The latest answer says that this problem has been fixed in the 15.4 update.

Can you confirm?

**Comment by cproof** [comment]
Thank you!
Yes I can confirm, it seems to work again with iOS 15.4

I'll update the code accordingly
